CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(120) UNIQUE,password VARCHAR(255),role VARCHAR(20) DEFAULT 'admin',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE invitations (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150),slug VARCHAR(150),theme_id INT,event_date DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE guests (id INT AUTO_INCREMENT PRIMARY KEY,invitation_id INT,name VARCHAR(120),phone VARCHAR(30),unique_token VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE rsvp (id INT AUTO_INCREMENT PRIMARY KEY,guest_name VARCHAR(120),attendance VARCHAR(20),guest_count INT,message TEXT,created_at DATETIME);
CREATE TABLE wishes (id INT AUTO_INCREMENT PRIMARY KEY,guest_name VARCHAR(120),message TEXT,created_at DATETIME);
CREATE TABLE themes (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80),slug VARCHAR(80),primary_color VARCHAR(20),secondary_color VARCHAR(20));
CREATE TABLE gallery (id INT AUTO_INCREMENT PRIMARY KEY,type VARCHAR(20),file_path VARCHAR(255),caption VARCHAR(160),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE music_playlist (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(120),artist VARCHAR(120),url VARCHAR(255),is_active TINYINT(1) DEFAULT 1);
CREATE TABLE visitor_logs (id INT AUTO_INCREMENT PRIMARY KEY,ip_address VARCHAR(60),user_agent VARCHAR(255),visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
