<?php
require __DIR__ . '/../config/helpers.php';
require __DIR__ . '/../config/database.php';
if (empty($_SESSION['buyer_id'])) { header('Location: /buyer/login'); exit; }
$buyerId=(int)$_SESSION['buyer_id'];
$buyer=$pdo->prepare('SELECT * FROM buyers WHERE id=?'); $buyer->execute([$buyerId]); $buyer=$buyer->fetch(PDO::FETCH_ASSOC);
$packages=$pdo->query('SELECT * FROM packages ORDER BY price')->fetchAll(PDO::FETCH_ASSOC);
$order=$pdo->prepare('SELECT o.*,p.name package_name,p.duration_days FROM orders o JOIN packages p ON p.id=o.package_id WHERE o.buyer_email=? ORDER BY o.id DESC LIMIT 1');$order->execute([$buyer['email']]);$order=$order->fetch(PDO::FETCH_ASSOC);
$themes=$pdo->query('SELECT id,name FROM themes')->fetchAll(PDO::FETCH_ASSOC);
$profile=$pdo->prepare('SELECT * FROM buyer_profiles WHERE buyer_id=?');$profile->execute([$buyerId]);$profile=$profile->fetch(PDO::FETCH_ASSOC);
?><!doctype html><html><head><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-zinc-950 text-white p-6"><div class="max-w-5xl mx-auto space-y-6"><h1 class="text-3xl font-bold">Buyer Panel</h1><p>Halo, <?= e($buyer['name']) ?> | <a class="underline" href="/buyer/logout">Logout</a></p>
<section class="bg-zinc-900 p-4 rounded-xl"><h2 class="font-semibold">Beli Masa Aktif</h2><form method="post" action="/api/order-create" class="grid md:grid-cols-3 gap-2 mt-2"><input type="hidden" name="buyer_name" value="<?= e($buyer['name']) ?>"><input type="hidden" name="buyer_email" value="<?= e($buyer['email']) ?>"><select name="package_id" class="p-2 rounded bg-zinc-800"><?php foreach($packages as $p) echo "<option value='{$p['id']}'>{$p['name']} - Rp".number_format($p['price'],0,',','.')."</option>"; ?></select><button class="bg-amber-400 text-black p-2 rounded">Checkout</button></form></section>
<section class="bg-zinc-900 p-4 rounded-xl"><h2 class="font-semibold">Status Order</h2><?php if($order): ?><p>#<?= $order['id']?> - <?= e($order['status'])?> - aktif sampai <?= e((string)$order['active_until'])?></p><?php if($order['status']!=='paid'): ?><form method="post" action="/api/order-mark-paid" class="mt-2"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="bg-blue-400 text-black px-3 py-1 rounded">Simulasi Bayar</button></form><?php endif; ?><?php else: ?><p>Belum ada order.</p><?php endif; ?></section>
<section class="bg-zinc-900 p-4 rounded-xl"><h2 class="font-semibold">Pilih Tema</h2><?php if($order && $order['status']==='paid' && strtotime((string)$order['active_until'])>time()): ?><form method="post" action="/api/select-theme" class="grid gap-2 mt-2"><input type="hidden" name="order_id" value="<?= $order['id'] ?>"><select name="theme_id" class="p-2 rounded bg-zinc-800"><?php foreach($themes as $t) echo "<option value='{$t['id']}'>{$t['name']}</option>";?></select><input class="p-2 rounded bg-zinc-800" name="title" placeholder="Judul undangan"><input class="p-2 rounded bg-zinc-800" name="slug" placeholder="slug-undangan"><button class="bg-fuchsia-400 text-black p-2 rounded">Simpan Tema</button></form><?php else: ?><p class="text-amber-300">Harus paid & aktif.</p><?php endif; ?></section>
<section class="bg-zinc-900 p-4 rounded-xl"><h2 class="font-semibold">Data Mempelai</h2><form method="post" action="/api/buyer-profile-save" class="grid md:grid-cols-2 gap-2 mt-2"><input name="invitation_title" class="p-2 rounded bg-zinc-800" placeholder="Judul" value="<?= e($profile['invitation_title'] ?? '') ?>"><input name="groom_name" class="p-2 rounded bg-zinc-800" placeholder="Nama Mempelai Pria" value="<?= e($profile['groom_name'] ?? '') ?>"><input name="bride_name" class="p-2 rounded bg-zinc-800" placeholder="Nama Mempelai Wanita" value="<?= e($profile['bride_name'] ?? '') ?>"><input name="event_date" type="datetime-local" class="p-2 rounded bg-zinc-800" value="<?= !empty($profile['event_date']) ? date('Y-m-d\TH:i', strtotime($profile['event_date'])) : '' ?>"><input name="event_location" class="p-2 rounded bg-zinc-800 md:col-span-2" placeholder="Lokasi" value="<?= e($profile['event_location'] ?? '') ?>"><textarea name="story" class="p-2 rounded bg-zinc-800 md:col-span-2" placeholder="Cerita cinta"><?= e($profile['story'] ?? '') ?></textarea><button class="bg-emerald-400 text-black p-2 rounded md:col-span-2">Simpan Profil</button></form></section>
</div></body></html>
